spring:
  application:
    name: stock-management

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: inventory
    password: inventory

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/master.xml

